spring:
  mongodb:
    password: test
    host: localhost
    port: 27017
    database: customer
    authentication-database: admin
    username: test
  kafka:
    consumer:
      bootstrap-servers: localhost:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: '*'
        spring.json.type.mapping: orderConfirmation:com.chaitya.ecommerce.kafka.order.OrderConfirmation,paymentConfirmation:com.chaitya.ecommerce.kafka.payment.PaymentConfirmation
      group-id: paymentGroup, orderGroup
      auto-offset-reset: earliest
  mail:
    host: localhost
    port: 1025
    username: test
    password: test
    properties:
      mail:
        smtp:
          trust: '*'
        auth: true
        starttls:
          enabled: true
        connectiontimeout: 5000
        timeout: 3000
        writetimeout: 5000

server:
  port: 8040